# Generated by Django 5.2.9 on 2026-05-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='discipline_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('stage_change', 'Stage Change'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('message', 'Message'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('clip_type', models.CharField(choices=[('reel', 'Reel'), ('performance', 'Performance'), ('commercial', 'Commercial'), ('short_film', 'Short Film'), ('music_video', 'Music Video'), ('headshot', 'Headshot')], default='reel', max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_set', to='api.talent')),
            ],
        ),
    ]
