# Generated by Django 5.2.9 on 2026-05-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application_notes_talent_discipline_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SELF_ASSERTED', 'Self Asserted'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified')], default='SELF_ASSERTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_verifications', to='api.talent')),
            ],
        ),
    ]
