# Generated by Django 5.2.14 on 2026-05-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feeditemcomment_report_subscriptiontier_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='availability_status',
            field=models.CharField(blank=True, default='Available', max_length=30),
        ),
        migrations.AddField(
            model_name='talent',
            name='availability_until',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='awards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='talent',
            name='endorsements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='talent',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='talent',
            name='name_audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='physical_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='talent',
            name='pinned_post_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='talent',
            name='training',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='talent',
            name='travel_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
