# Generated by Django 5.2.9 on 2026-05-27 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_extend_talent_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=80, unique=True)),
                ('primary_discipline', models.CharField(choices=[('actor', 'Actor'), ('singer', 'Singer'), ('dancer', 'Dancer'), ('musician', 'Musician'), ('voice_actor', 'Voice Actor'), ('comedian', 'Comedian'), ('presenter', 'Presenter'), ('director', 'Director')], default='actor', max_length=30)),
                ('secondary_disciplines', models.JSONField(blank=True, default=list)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('playable_age_min', models.IntegerField(default=18)),
                ('playable_age_max', models.IntegerField(default=35)),
                ('identity_verified', models.BooleanField(default=False)),
                ('headshots', models.JSONField(blank=True, default=list)),
                ('cover_image', models.JSONField(blank=True, null=True)),
                ('representation', models.JSONField(blank=True, null=True)),
                ('following_count', models.IntegerField(default=0)),
                ('talent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artstage_profile', to='api.talent')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='ArtStagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('platform_only', 'Platform Only'), ('industry_only', 'Industry Only'), ('scout_only', 'Scout Only'), ('private', 'Private')], default='public', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artstage_posts', to='api.talent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('available', 'Available'), ('tentative', 'Tentative'), ('unavailable', 'Unavailable'), ('booked', 'Booked')], default='available', max_length=15)),
                ('willing_to_travel', models.BooleanField(default=True)),
                ('travel_radius', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='api.talent')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('production_type', models.CharField(max_length=50)),
                ('billing', models.CharField(blank=True, max_length=50)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('producing_entity', models.CharField(blank=True, max_length=150)),
                ('verification', models.CharField(choices=[('self_asserted', 'Self Asserted'), ('pending', 'Pending'), ('verified', 'Verified')], default='self_asserted', max_length=20)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artstage_credits', to='api.talent')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('capacity', models.IntegerField(default=100)),
                ('is_virtual', models.BooleanField(default=False)),
                ('stream_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_live', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('viewer_count', models.IntegerField(default=0)),
                ('co_hosts', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('platform_only', 'Platform Only'), ('industry_only', 'Industry Only')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='api.talent')),
            ],
        ),
        migrations.CreateModel(
            name='PostStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.artstagepost')),
            ],
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('monologue', 'Monologue'), ('song', 'Song'), ('dance', 'Dance'), ('voice_demo', 'Voice Demo'), ('comedy', 'Comedy'), ('reel', 'Showreel'), ('cover', 'Cover')], default='reel', max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('platform_only', 'Platform Only'), ('industry_only', 'Industry Only'), ('scout_only', 'Scout Only'), ('private', 'Private')], default='public', max_length=20)),
                ('scout_expires_at', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('has_captions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artstage_reels', to='api.talent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Duet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('layout', models.CharField(choices=[('side_by_side', 'Side by Side'), ('picture_in_picture', 'Picture in Picture'), ('reaction', 'Reaction')], default='side_by_side', max_length=25)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('platform_only', 'Platform Only'), ('industry_only', 'Industry Only'), ('scout_only', 'Scout Only'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duets', to='api.talent')),
                ('original_reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duet_responses', to='api.reel')),
            ],
        ),
        migrations.CreateModel(
            name='ReelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.reel')),
            ],
        ),
        migrations.CreateModel(
            name='UnionAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('financial_core', 'Financial Core'), ('eligible', 'Eligible')], default='active', max_length=20)),
                ('joined_year', models.IntegerField()),
                ('verification', models.CharField(choices=[('self_asserted', 'Self Asserted'), ('pending', 'Pending'), ('verified', 'Verified')], default='self_asserted', max_length=20)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_affiliations', to='api.talent')),
            ],
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.event')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
