# Generated by Django 5.2.14 on 2026-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_artistprofile_artstagepost_availabilitywindow_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='portfolio_submissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='questionnaire_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='portfolio_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='questionnaire',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('Shortlisted', 'Shortlisted'), ('Callback', 'Callback'), ('Approved', 'Approved'), ('Hired', 'Hired')], default='New', max_length=50),
        ),
    ]
