# Generated by Django 5.2.9 on 2026-05-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_application_portfolio_submissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='author_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
