# Generated by Django 5.2.9 on 2026-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_feeditem_author_avatar_alter_feeditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
