# Generated by Django 5.2.9 on 2026-05-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reelcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
