# Generated by Django 5.2.9 on 2026-05-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='submission_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clip',
            name='accent',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='clip',
            name='download_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clip',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clip',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('platform_only', 'Platform Only')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='talent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='external_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='talent',
            name='field_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='talent',
            name='legal_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='talent',
            name='press_mentions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='talent',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('platform_only', 'Platform Only'), ('industry_only', 'Industry Only'), ('stealth', 'Stealth')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='talent',
            name='sub_disciplines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='primary_discipline',
            field=models.CharField(choices=[('actor', 'Actor'), ('singer', 'Singer'), ('dancer', 'Dancer'), ('musician', 'Musician'), ('voice_actor', 'Voice Actor'), ('comedian', 'Comedian'), ('presenter', 'Presenter'), ('director', 'Director'), ('choreographer', 'Choreographer'), ('composer', 'Composer'), ('screenwriter', 'Screenwriter'), ('cinematographer', 'Cinematographer'), ('visual_artist', 'Visual Artist'), ('model', 'Model'), ('stage_technician', 'Stage Technician')], default='actor', max_length=30),
        ),
        migrations.CreateModel(
            name='SkillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('language', 'Language'), ('accent', 'Accent/Dialect'), ('instrument', 'Instrument'), ('dance_style', 'Dance Style'), ('vocal', 'Vocal'), ('physical', 'Physical Skill'), ('driving', 'Driving License'), ('specialty', 'Specialty')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=20)),
                ('endorsed_by', models.JSONField(blank=True, default=list)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='api.talent')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
