# Generated by Django 5.2.9 on 2026-05-29 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_artist_profile_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='onboarding_steps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='credit',
            name='collaborators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('skill_category', models.CharField(blank=True, max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_endorsements', to='api.talent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('talent', 'author')},
            },
        ),
    ]
