# Generated by Django 5.2.9 on 2026-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_artistprofile_onboarding_steps_credit_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='audio_waveform',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reel',
            name='captions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reel',
            name='download_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reel',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reel',
            name='version_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reel',
            name='watermark_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('Shortlisted', 'Shortlisted'), ('Callback', 'Callback'), ('Approved', 'Approved'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='reel',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('platform_only', 'Platform Only'), ('industry_only', 'Industry Only'), ('scout_only', 'Scout Only'), ('link_only', 'Link Only'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
