# Generated by Django 5.2.9 on 2026-05-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_application_rejected_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='clip_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='download_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pdf_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='review_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('starred', 'Starred'), ('flagged', 'Flagged'), ('passed', 'Passed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='selected_take',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='shared_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='slate_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='star_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='takes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='visibility_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='watermark_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='prompt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='submission_type',
            field=models.CharField(choices=[('PROFILE_ONLY', 'Profile Only'), ('SELF_TAPE', 'Self-Tape Video'), ('AUDIO', 'Audio Only'), ('LIVE_AUDITION', 'Live Audition Slot'), ('WRITTEN', 'Written / PDF')], default='SELF_TAPE', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='api.application')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('location_or_link', models.CharField(blank=True, max_length=500)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='audition_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.auditionslot'),
        ),
        migrations.CreateModel(
            name='CallbackRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_rounds', to='api.application')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_rounds', to='api.opportunity')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
