# Generated by Django 5.2.9 on 2026-05-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_postlike_postsave_reellike_reelsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='category',
            field=models.CharField(blank=True, default='artist', max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
