# Generated by Django 5.2.9 on 2026-05-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_make_talent_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='api.feeditem'),
        ),
    ]
