# Generated by Django 5.2.14 on 2026-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_feeditem_repost_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('Shortlisted', 'Shortlisted'), ('Callback', 'Callback'), ('Approved', 'Approved'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], db_index=True, default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='talent',
            name='availability_status',
            field=models.CharField(blank=True, db_index=True, default='Available', max_length=30),
        ),
        migrations.AlterField(
            model_name='talent',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='artist', max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
