# Generated by Django 5.2.9 on 2026-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_livechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
