# Generated by Django 5.2.14 on 2026-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_feeditem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
