# Generated by Django 5.2.9 on 2026-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_artistprofile_onboarding_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
