# Generated by Django 5.2.14 on 2026-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_feeditem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='unionaffiliation',
            name='joined_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unionaffiliation',
            name='status',
            field=models.CharField(blank=True, default='Member', max_length=50, null=True),
        ),
    ]
