# Generated by Django 5.2.14 on 2026-06-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_connection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='playable_age_max',
            field=models.IntegerField(blank=True, default=35, null=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='playable_age_min',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
