export const talents = [
  {
    id: "1",
    name: "Layla Hassan",
    stageName: "Layla H.",
    category: "Actress",
    subcategory: "Film & TV",
    location: "Cairo, Egypt",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=layla",
    coverGradient: "from-violet-900 to-indigo-900",
    verified: true,
    featured: true,
    followers: 48200,
    views: 320000,
    auditions: 34,
    rating: 4.9,
    bio: "Award-winning actress with 8 years of experience in Egyptian cinema and international productions. Known for emotionally compelling roles and multilingual performance ability.",
    skills: ["Method Acting", "Arabic", "English", "French", "Stage Combat", "Dance"],
    credits: ["The Cairo Files (2023)", "Mediterranean Dreams (2022)", "Desert Rose TV Series (2021)"],
    badges: ["Verified Actor", "Top Talent 2024", "Agency Represented"],
    agency: "StarGate Talent Agency",
    union: "Egyptian Actors Guild",
    reelUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    socialLinks: { instagram: "laylahassan", tiktok: "laylaacts" },
    availability: "Available from July 2024",
    languages: ["Arabic", "English", "French"],
  },
  {
    id: "2",
    name: "Omar Khalid",
    stageName: "OK Music",
    category: "Musician",
    subcategory: "R&B / Soul",
    location: "Dubai, UAE",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=omar",
    coverGradient: "from-amber-900 to-orange-900",
    verified: true,
    featured: true,
    followers: 125000,
    views: 890000,
    auditions: 12,
    rating: 4.8,
    bio: "Multi-platinum R&B artist and producer. Featured on 3 Grammy-nominated albums. Creating soulful music that bridges Arabic and Western genres.",
    skills: ["Vocals", "Piano", "Music Production", "Songwriting", "Arabic Maqam"],
    credits: ["'Golden Light' EP (2023)", "Feature on Beyoncé Remix", "Dubai Expo World Stage"],
    badges: ["Verified Artist", "Label Signed", "Platinum Record"],
    agency: "Universal Music MENA",
    union: "Musicians Union UAE",
    reelUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    socialLinks: { instagram: "okmusic", spotify: "okmusic" },
    availability: "Bookings open Q3 2024",
    languages: ["Arabic", "English"],
  },
  {
    id: "3",
    name: "Nour El-Din",
    stageName: "NourDance",
    category: "Dancer",
    subcategory: "Contemporary / Hip-Hop",
    location: "Beirut, Lebanon",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nour",
    coverGradient: "from-pink-900 to-rose-900",
    verified: false,
    featured: false,
    followers: 22000,
    views: 156000,
    auditions: 18,
    rating: 4.7,
    bio: "Contemporary and hip-hop dancer with training at the Lebanese National Conservatory. Choreographer for 3 regional music video productions.",
    skills: ["Contemporary", "Hip-Hop", "Choreography", "Acrobatics", "Ballet"],
    credits: ["MBC Dance Battle S2", "Fairuz Tribute Show", "Adidas MENA Campaign"],
    badges: ["Rising Star"],
    agency: null,
    union: null,
    reelUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    socialLinks: { instagram: "nourdance", tiktok: "nourdance" },
    availability: "Available Now",
    languages: ["Arabic", "French"],
  },
  {
    id: "4",
    name: "Sara Mostafa",
    stageName: "Sara M",
    category: "Model",
    subcategory: "Editorial / Commercial",
    location: "Cairo, Egypt",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sara",
    coverGradient: "from-teal-900 to-cyan-900",
    verified: true,
    featured: false,
    followers: 89000,
    views: 540000,
    auditions: 56,
    rating: 4.9,
    bio: "International model and creative director. Walked for Elie Saab, Dior Middle East, and featured in Vogue Arabia 3 consecutive years.",
    skills: ["Editorial", "Commercial", "Runway", "Brand Campaigns", "Art Direction"],
    credits: ["Vogue Arabia (2022, 2023, 2024)", "Elie Saab SS24", "L'Oréal MENA Campaign"],
    badges: ["Verified Model", "Agency Represented", "Vogue Featured"],
    agency: "Elite Model Cairo",
    union: null,
    reelUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    socialLinks: { instagram: "sarammodel" },
    availability: "Selective bookings",
    languages: ["Arabic", "English", "Italian"],
  },
];

export const recruiters = [
  {
    id: "r1",
    name: "Ahmed Fouad",
    title: "Casting Director",
    company: "Cairo Film Studios",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed",
    verified: true,
    hires: 340,
    activePostings: 8,
    specialty: ["Feature Films", "TV Series", "Commercials"],
  },
  {
    id: "r2",
    name: "Maya Saleh",
    title: "A&R Manager",
    company: "Universal Music MENA",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya",
    verified: true,
    hires: 89,
    activePostings: 4,
    specialty: ["R&B", "Pop", "Electronic"],
  },
  {
    id: "r3",
    name: "Karim Nabil",
    title: "Talent Scout",
    company: "StarGate Talent Agency",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=karim",
    verified: true,
    hires: 210,
    activePostings: 12,
    specialty: ["Acting", "Modeling", "Hosting"],
  },
];

export const opportunities = [
  {
    id: "o1",
    title: "Lead Actress — Feature Film 'Nile Noir'",
    company: "Cairo Film Studios",
    companyLogo: "Film",
    type: "Film Role",
    category: "Acting",
    location: "Cairo, Egypt",
    compensation: "EGP 150,000",
    deadline: "2024-07-15",
    posted: "2 days ago",
    applicants: 47,
    description: "Seeking a lead actress (25-35) for a psychological thriller set in Cairo. Fluent Arabic required. 6-week shoot starting August 2024.",
    requirements: ["Female", "Age 25-35", "Fluent Arabic", "Strong dramatic range", "Available Aug–Sep 2024"],
    tags: ["Lead Role", "Feature Film", "Paid", "Cairo"],
    featured: true,
    urgent: false,
  },
  {
    id: "o2",
    title: "R&B Vocalist for Studio Album",
    company: "Universal Music MENA",
    companyLogo: "Music",
    type: "Music Collaboration",
    category: "Music",
    location: "Dubai, UAE",
    compensation: "Negotiable + Royalties",
    deadline: "2024-07-30",
    posted: "5 days ago",
    applicants: 83,
    description: "Major label seeking an R&B vocalist for a 12-track studio album. Looking for someone who can blend Arabic and English vocals.",
    requirements: ["Bilingual Arabic/English", "R&B vocal range", "Studio experience", "Available Q3 2024"],
    tags: ["Studio Album", "Music", "Label", "Royalties"],
    featured: true,
    urgent: true,
  },
  {
    id: "o3",
    title: "Commercial Dancers — Pepsi MENA Campaign",
    company: "Draft FCB Dubai",
    companyLogo: "Activity",
    type: "Commercial",
    category: "Dance",
    location: "Dubai, UAE",
    compensation: "USD 3,000/day",
    deadline: "2024-06-28",
    posted: "1 week ago",
    applicants: 124,
    description: "Casting 6 dancers for a high-energy Pepsi commercial. Looking for strong contemporary/hip-hop styles. 2-day shoot.",
    requirements: ["Contemporary or Hip-Hop", "Age 18-28", "High energy performance", "Available June 28-30"],
    tags: ["Commercial", "Dance", "High Pay", "Urgent"],
    featured: false,
    urgent: true,
  },
  {
    id: "o4",
    title: "Fashion Model — Vogue Arabia Editorial",
    company: "Condé Nast Middle East",
    companyLogo: "Camera",
    type: "Editorial",
    category: "Modeling",
    location: "Abu Dhabi, UAE",
    compensation: "USD 5,000 + exposure",
    deadline: "2024-07-10",
    posted: "3 days ago",
    applicants: 35,
    description: "Vogue Arabia seeking high-fashion editorial models for the September 2024 issue. Luxury fashion experience preferred.",
    requirements: ["Height 175cm+", "Editorial experience", "Portfolio required", "Available July 5-8"],
    tags: ["Editorial", "Vogue", "High Fashion", "Premium"],
    featured: true,
    urgent: false,
  },
  {
    id: "o5",
    title: "Voice Actor — Arabic Animation Series",
    company: "MBC Kids",
    companyLogo: "Mic",
    type: "Voice Acting",
    category: "Voice",
    location: "Remote",
    compensation: "EGP 8,000/episode",
    deadline: "2024-08-01",
    posted: "1 day ago",
    applicants: 28,
    description: "Seeking Arabic-speaking voice actors for a 26-episode children's animation series. Multiple character roles available.",
    requirements: ["Native Arabic speaker", "Voice acting experience", "Home studio preferred", "Long-term commitment"],
    tags: ["Voice Acting", "Animation", "Remote", "Recurring"],
    featured: false,
    urgent: false,
  },
  {
    id: "o6",
    title: "Host / MC — Dubai Tech Summit 2024",
    company: "GITEX Global",
    companyLogo: "Mic",
    type: "Event Hosting",
    category: "Hosting",
    location: "Dubai, UAE",
    compensation: "USD 8,000",
    deadline: "2024-07-01",
    posted: "4 days ago",
    applicants: 19,
    description: "Seeking a bilingual professional host for the Dubai Tech Summit. Must be confident, charismatic, and knowledgeable about tech trends.",
    requirements: ["Bilingual Arabic/English", "Event hosting experience", "Professional appearance", "Tech-savvy"],
    tags: ["Hosting", "Corporate", "Premium", "Bilingual"],
    featured: false,
    urgent: true,
  },
];

export const feedItems = [
  {
    id: "f1",
    creator: { name: "Layla Hassan", category: "Actress", avatar: "LH", verified: true },
    title: "Audition Reel — Cairo Film Studios",
    description: "My self-tape for the Nile Noir lead role. Three years of preparation for this moment 🎬",
    category: "Acting",
    gradient: "from-violet-600 via-purple-700 to-indigo-800",
    emoji: "Film",
    likes: 4820,
    comments: 231,
    shares: 89,
    saves: 412,
    watchTime: "1:34",
    recruiterSaves: 23,
    tags: ["Acting", "Drama", "Reel"],
  },
  {
    id: "f2",
    creator: { name: "Omar Khalid", category: "Musician", avatar: "OK", verified: true },
    title: "Studio Session — New EP Teaser",
    description: "Sneak peek of my new R&B track blending Arabic maqam with modern production 🎵",
    category: "Music",
    gradient: "from-amber-600 via-orange-700 to-red-800",
    emoji: "Music",
    likes: 12400,
    comments: 567,
    shares: 340,
    saves: 890,
    watchTime: "0:58",
    recruiterSaves: 67,
    tags: ["Music", "R&B", "Studio"],
  },
  {
    id: "f3",
    creator: { name: "Nour El-Din", category: "Dancer", avatar: "ND", verified: false },
    title: "Contemporary Choreography — Original Piece",
    description: "My latest contemporary piece inspired by Fairuz classics. 6 months in the making 💃",
    category: "Dance",
    gradient: "from-pink-600 via-rose-700 to-red-800",
    emoji: "Activity",
    likes: 8930,
    comments: 412,
    shares: 201,
    saves: 634,
    watchTime: "2:10",
    recruiterSaves: 41,
    tags: ["Dance", "Contemporary", "Original"],
  },
  {
    id: "f4",
    creator: { name: "Sara Mostafa", category: "Model", avatar: "SM", verified: true },
    title: "Behind the Scenes — Vogue Arabia Shoot",
    description: "A glimpse into my day on set for the Vogue Arabia September 2024 issue ✨",
    category: "Modeling",
    gradient: "from-teal-600 via-cyan-700 to-blue-800",
    emoji: "Sparkles",
    likes: 21300,
    comments: 891,
    shares: 456,
    saves: 1240,
    watchTime: "1:15",
    recruiterSaves: 89,
    tags: ["Modeling", "Fashion", "BTS"],
  },
  {
    id: "f5",
    creator: { name: "Khalid Ibrahim", category: "Comedian", avatar: "KI", verified: false },
    title: "Stand-Up Set — Arabic Comedy Special",
    description: "5 minute excerpt from my upcoming Netflix MENA special. Let me know what you think! 😂",
    category: "Comedy",
    gradient: "from-yellow-600 via-amber-700 to-orange-800",
    emoji: "Smile",
    likes: 34500,
    comments: 1230,
    shares: 780,
    saves: 890,
    watchTime: "5:02",
    recruiterSaves: 34,
    tags: ["Comedy", "Stand-Up", "Netflix"],
  },
  {
    id: "f6",
    creator: { name: "Dina Farouk", category: "Voice Actor", avatar: "DF", verified: true },
    title: "Voice Demo Reel 2024",
    description: "Updated demo showcasing my range across animation, commercial, and dramatic styles 🎙️",
    category: "Voice",
    gradient: "from-emerald-600 via-green-700 to-teal-800",
    emoji: "Mic",
    likes: 3240,
    comments: 156,
    shares: 78,
    saves: 289,
    watchTime: "2:45",
    recruiterSaves: 56,
    tags: ["Voice Acting", "Demo Reel", "Animation"],
  },
];

export const connections = [
  { id: "c1", name: "Ahmed Fouad", role: "Casting Director", company: "Cairo Film Studios", mutual: 12, avatar: "AF" },
  { id: "c2", name: "Maya Saleh", role: "A&R Manager", company: "Universal Music MENA", mutual: 8, avatar: "MS" },
  { id: "c3", name: "Reem Khalil", role: "Actress", company: "Independent", mutual: 23, avatar: "RK" },
  { id: "c4", name: "Hassan Ali", role: "Music Producer", company: "Sound Factory Egypt", mutual: 5, avatar: "HA" },
  { id: "c5", name: "Farah Nasser", role: "Talent Agent", company: "StarGate Agency", mutual: 17, avatar: "FN" },
  { id: "c6", name: "Youssef Magdy", role: "Director", company: "Synergy Films", mutual: 9, avatar: "YM" },
];

export const messages = [
  {
    id: "m1",
    from: "Ahmed Fouad",
    role: "Casting Director",
    avatar: "AF",
    preview: "I saw your reel for Nile Noir — very impressive. Are you available for a callback next week?",
    time: "2m ago",
    unread: true,
    verified: true,
  },
  {
    id: "m2",
    from: "Maya Saleh",
    role: "A&R Manager",
    avatar: "MS",
    preview: "We'd love to discuss a potential collaboration on our upcoming MENA project...",
    time: "1h ago",
    unread: true,
    verified: true,
  },
  {
    id: "m3",
    from: "StarGate Agency",
    role: "Talent Agency",
    avatar: "SG",
    preview: "Your profile has caught our attention. We represent some of Egypt's top talent and...",
    time: "3h ago",
    unread: false,
    verified: true,
  },
  {
    id: "m4",
    from: "Karim Nabil",
    role: "Talent Scout",
    avatar: "KN",
    preview: "Following up on our conversation from the Cairo Film Festival. We have an exciting opportunity...",
    time: "Yesterday",
    unread: false,
    verified: true,
  },
];

export const applications = [
  {
    id: "a1",
    opportunityId: "o1",
    talentId: "1",
    stage: "Callback",
    coverNote: "Hi Ahmed! I've been a huge fan of your work at Cairo Film Studios. I'm highly fluent in both Arabic and English, and have 8 years of dramatic acting experience. I've attached my reel from 'The Cairo Files'.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    submittedAt: "2024-05-20T10:00:00Z"
  },
  {
    id: "a2",
    opportunityId: "o1",
    talentId: "3",
    stage: "New",
    coverNote: "I'm primarily a dancer but I have taken acting classes at the conservatory. Would love to be considered.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    submittedAt: "2024-05-22T14:30:00Z"
  },
  {
    id: "a3",
    opportunityId: "o1",
    talentId: "4",
    stage: "Shortlisted",
    coverNote: "I have strong on-screen presence from my commercial modeling work. I've attached a recent self-tape.",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    submittedAt: "2024-05-21T09:15:00Z"
  }
];
